on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:          
  docker:
    name: Containerization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v4
        with:
          context: front_voting_app
          push: false
          tags: kennetchofo/frontend-voting-app:${{ github.sha }}

      - name: Docker Image Test
        run: |
          echo "📦 Images construites :"
          docker images

          echo "🚀 Lancement du container pour test"
          docker run -d --name votingApp kennetchofo/frontend-voting-app:${{ github.sha }}

          echo "📄 Logs du container :"
          docker logs votingApp

          echo "🧹 Nettoyage du container"
          docker stop votingApp
          docker rm votingApp
